version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo_bd
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/csantiago/Projects/docker/mongo/db:/data/db
